---

- name: node apt stuff
  shell: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -"
  args:
    warn: false
  tags:
    - node-apt-source


- name: Install nodejs
  apt:
    name: nodejs
    state: present


- name: install pm2
  npm:
    name: pm2
    global: yes
  tags:
    - npm
    - pm2
    

- name: npm ci
  # https://docs.npmjs.com/cli/ci
  shell: 'cd /srv/trustroots && npm ci'
  become: yes
  become_user: guaka
  tags:
    - install

## TODO: make var in 'shell' come form playbook
## TODO:figure this out
## TODO: remove env here, it shoyld be in playbook
## get rind of the OR TRUE that fixes the broken population stuff
- name: npm run build:dev
  shell: 'cd /srv/trustroots && npm run build:dev || true '
  become: yes
  become_user: guaka
#  environment:
#    NODE_ENV: development
  tags:
    - build
  

## TODO: get rid of the need for OR TRUE
- name: generate test data
  shell: 'cd /srv/trustroots && npm run seed > /dev/null || true'
  become: yes
  become_user: guaka
  tags:
    - testdata
    

- name: pm2 start
#  shell: 'cd /srv/trustroots && pm2 start worker-pm2.json --env production'
  shell: 'cd /srv/trustroots && pm2 start worker-pm2.json --env development'
  become: yes
  become_user: guaka
  tags:
    - pm2

